/*Drop any existing table if any*/

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS reserve;

/*Create Table for user and task*/

CREATE TABLE users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email VARCHAR(255),
name VARCHAR(20),
password VARCHAR(50)
);

CREATE TABLE reserve(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id INTEGER, 
title VARCHAR(100),
description TEXT,
status VARCHAR(200),
start_date DATE,
finish_date DATE,
created_date DATE,
roomnumber INTEGER,
categry INTEGER,
);